AWSTemplateFormatVersion: 2010-09-09
Description: >
  Sample template 
Resources: 
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl:  BucketOwnerFullControl
      BucketName: abcdefg